# usuario-service.yaml
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: usuario-service
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
      - image: aluna1997/usuario-service:1.0
        env:
        - name: SPRING_DATA_MONGODB_URI
          value: "mongodb://mongodb:27017/usuarios"
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"